### ISSUE TITLE
Criar categorias dinâmicas

### ISSUE THREAD

**Issue by leandro-costa** [resepemb/app-super-info#1]

**Comment by GabrielCoffee9** [comment]
Em breve será implementado aqui no app-super-info. As categorias dinâmicas já estão funcionando no repositório quarto-blog-test

**Comment by GabrielCoffee9** [comment]
As categorias dinâmicas foram implementadas, agora basta definir como elas vão ser utilizadas na página index.qmd através do script que gera o arquivo .ejs
