### ISSUE TITLE
remover dependências externas script de post-render

### ISSUE THREAD

**Issue by leandro-costa** [resepemb/app-super-info#7]
Ao executar o `quarto preview` no windows o comando `cp` apresenta erro.
E é necessário o `node` instalado no SO, o que não deveria.

- [x] #9
- [x] #11

**Comment by GabrielCoffee9** [comment]
As issues foram resolvidas, agora não é mais necessário o node instalado no SO. 
Infelizmente o workbox-build só existe como um modulo node e a pasta node_modules tem que existir localmente para que o deno offline consiga acessar. Por isto, no ultimo commit a pasta node_modules foi retirada do .gitignore.
